### PR TITLE
Rename cloud_type from GCE to GCP, clarify throughout

### PR DESCRIPTION
**Pull request by eolix**
`cloud_type` was renamed from `gce` to `gcp` to maintain consistency with the aws/ec2 documentation and usage throughout the playbook.

It introduces one breaking change for playbooks that run on GCP, as the `cloud_type` variable would have to be renamed.

### CODE REVIEW

**Comment by dseeley-sky** [comment]
Theoretically, application playbooks should not have a dependency upon `clusterverse`'s cluster_vars, so this _should_ not be a breaking change...

**Comment by dseeley-sky** [comment]
Contrary to my earlier statement, the change will require all application playbooks that use clusterverse with GCP to change the `cloud_type` in their `cluster_vars`, (as Patrik mentioned initially).  Is it worth forcing everyone else to change their application playbooks for what is essentially a cosmetic change?

**Comment by dseeley-sky** [comment]
> Contrary to my earlier statement, the change will require all application playbooks that use clusterverse with GCP to change the `cloud_type` in their `cluster_vars`, (as Patrik mentioned initially). Is it worth forcing everyone else to change their application playbooks for what is essentially a cosmetic change?

Maybe there are few enough users within GCP that this has a fairly small impact right now?

**Comment by eolix** [comment]
It was my thought as well as this is, by all means, a cosmetic change. However, with a wider GCP adoption in the future this might get flagged nonetheless.

The expected changes from Clusterverse/GCP user point-of-view is a one-liner:
```
cluster_vars:
  type: gcp
```
... so I doubt it will create much backlash. What are your thoughts @mikekrasn and @flfernandez ?

**Comment by mikekrasn** [comment]
The change is indeed minimal from a user perspective. I personally agree with it.

**Comment by leslieonline27** [comment]
Currently for Persistence there is no worries changing this, but I know that Content Discovery used clusterverse for their Couchbase build out in GCP towards the end of last year.  I think we'd need to sync with them on this change, but as Patrik's said it's a small modification of the cloud type value so I don't think it would be an issue

**Comment by eolix** [comment]
@sky-amoncadot : I don't know who picked up the Couchbase work in CD, as KL has left the department, but from your perspective would this be a major impacting change?

**Comment by eolix** [comment]
Confirmed by @PreeyanP this isn't an issue for CD

**Pull request merged**
