### PR TITLE
[FEATURE] ec2 to ec2_instance 

### PR DESCRIPTION
**Pull request by FredButler**
Move from ec2 to `amazon.aws.ec2_instance` module.
volumes structure changed for `ec2_instance`; maintain old syntax in `cluster_defs`.
Spot instances no longer supported

`Chrony` changes showing although already merged

### CODE REVIEW

**Review by JamalSky — APPROVED** [review]
LGTM 🚀

**Review by dipiazzg — APPROVED** [review]
LGTM

**Review by dro25 — APPROVED** [review]

**Review by antoineserrano — APPROVED** [review]
Sad to see support for Spot instances going away...

**Comment by dseeley** [comment]
Looks familiar (c.f. https://github.com/dseeley/clusterverse/commit/e832c5f274d04d2e21559be4debc27dbe183fd8e)!!

There are a few other changes & fixes in there that might be useful, e.g. 
+ `amazon.aws.ec2_instance` doesn't return the `tagged_instances` structure if the instances already exist, so the playbook would not be idempotent (& I think this kills one or two of the redeploy schemes).
+ You need Ansible core >=2.12.4 (or pypi v5.6.0) now, so the preflight assertions should change (they actually get a bit simpler).
+ I found that the route53 rescue mechanism (create_dns_a.yml) wasn't working, as the `module_args` were not present anymore, hence these values are acquired from elsewhere.

**Pull request merged**
