### PR TITLE
Create a new redeploy scheme (_scheme_rmvm_keepdisk_rollback), which moves disks from old to new VMs

### PR DESCRIPTION
**Pull request by dseeley**
+ Create a new redeploy scheme (_scheme_rmvm_keepdisk_rollback), which moves disks between old and new VMs, saving a lot of time.
+ Prevent users from specifying non-ephemeral disks as /dev/sd[b-e] as this is not supported by AWS. Running cluster.yml against an existing cluster (one that was built with sd[b-e] names) with the cluster_vars device_names corrected to sd[f-p] will not cause a problem as the EC2 module does not modify disks when run against an existing VM.
+ Add labels to the disks
+ Replace the disks_auto logic to use the actual mapping of AWS device name to OS device name. This is necessary to support the disk moving scheme, and is much more reliable; include the 'blockdevmap' module from https://github.com/dseeley/blockdevmap to do this.
+ Mount disks using UUID instead of device string, as with nvme disks, the device names can change between restarts (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#identify-nvme-ebs-device).
+ Create a variable (redeploy_schemes_supported), which prevents the accidental use of a redeploy scheme that might (for example) cause data loss.

### CODE REVIEW

**Comment by mikekrasn** [comment]
The scheme has been tested and worked really good. One thing that could be an issue though:
- It is not possible to specify **root volume** size as or other parameters for it as fstype is a mandatory variable for a disk (it was possible in previous clusterverse version)

**Comment by dseeley** [comment]
> The scheme has been tested and worked really good. One thing that could be an issue though:
> 
> * It is not possible to specify **root volume** size as or other parameters for it as fstype is a mandatory variable for a disk (it was possible in previous clusterverse version)

This is an interesting problem.  It happens because the information that AWS insert in the NVMe controller's 'Vendor' section is returned for the disk _as well as_ the disk's first partition, so the nvme mapping of the root disk (e.g. /dev/nvme0n1) appears to be mapped to /dev/sda1, when in fact, only the first _partition_ (/dev/nvme0n1**p1**) should be mapped.  

The PTTYPE option of lsblk cannot be used here as it is not supported in older Linux builds of lsblk (e.g. CentOS7).  There are alternatives...

**Comment by dseeley** [comment]
> The scheme has been tested and worked really good. One thing that could be an issue though:
> 
> * It is not possible to specify **root volume** size as or other parameters for it as fstype is a mandatory variable for a disk (it was possible in previous clusterverse version)

I believe this is fixed by: https://github.com/sky-uk/clusterverse/pull/72/commits/775ac6dd201e0e3b34953d219e03e8843cc742ce

**Review by antoineserrano — APPROVED** [review]
Tested creation, deletion + new redeploy scheme/redeploy scheme restriction. Couldn't find any major issue.

**Pull request merged**
